### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by yarikbratashchuk** [koding/tunnel#44]
Hello)

I have a problem.
I need a request that goes to sub.example.com:8080 to hit localhost:3000.
How should i config client for that?
Seems like `ClientConfig.LocalAddr:":3000"` does not help.

It does work locally. but i try to run it on appengine and always get `no client session established` error.

Thanks a lot)

**Comment by cihangir** [comment]
Hi @yarikbratashchuk 
We haven't tested tunnel on appengine. In some cases appengine requires some additional work/configuration, you might be hitting that edge.

**Comment by yarikbratashchuk** [comment]
Hi @cihangir 

Thanks for the answer.
