### ISSUE TITLE
yamux: keepalive failed: session shutdown

### ISSUE THREAD

**Issue by yarikbratashchuk** [koding/tunnel#45]
Hi)

I wonder how to reconnect client if errors like: 
```
yamux: keepalive failed: session shutdown
```
```
yamux: keepalive failed: i/o deadline reached
```
appears?

Thanks for help)

**Comment by rjeczalik** [comment]
You can subscribe for [connection state changes here](https://github.com/koding/tunnel/blob/master/client.go#L140) and write your own handling.

Will that work for you?

**Comment by yarikbratashchuk** [comment]
Thanks for reply. 
So if i know that connection is dropped, what should i do? Run ```client.Start()``` to reconnect?
Or i should do something with ```ClientConfig.Backoff```?

**Comment by rjeczalik** [comment]
@yarikbratashchuk Sorry, I misread your question. Client automatically reconnects if the underlying connection is gone. I thought you wanted some extra handling.

**Comment by yarikbratashchuk** [comment]
Thanks for reply)

**Comment by rjeczalik** [comment]
You're welcome!
